name: C++ CI with CMake and Matrix

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        test_target: [unit_tests]  # Add stress_tests here later: [unit_tests, stress_tests]

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      TEST_TARGET: ${{ matrix.test_target }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake (${{ env.BUILD_TYPE }})
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build target (${{ env.TEST_TARGET }})
        run: cmake --build build --target ${{ env.TEST_TARGET }}

      - name: Run target binary (${{ env.TEST_TARGET }})
        run: ./build/${{ env.TEST_TARGET }}
